### ISSUE TITLE
SPM Support.

### ISSUE THREAD

**Issue by xpnewmedia** [team-telnyx/telnyx-webrtc-ios#56]
Thank for this demo/lib.

Anyway to get Swift Package Manager support on this Library.

Things get wacky with cocoapods and SPM both involved in the project.
Trying to keep development streamlined.

Thank You.

**Comment by paulgkramer** [comment]
Hi @xpnewmedia, thanks for your comment. Could you please join the Telnyx Dev Slack channel and post this request? https://joinslack.telnyx.com/

**Comment by RJSkorski** [comment]
@xpnewmedia SPM is supported by iOS SDK at the moment
