### ISSUE TITLE
Push Notifications Isuue

### ISSUE THREAD

**Issue by hpsolver** [team-telnyx/telnyx-webrtc-ios#70]
i have follow this doc for setup notification : https://developers.telnyx.com/docs/v2/webrtc/push-notifications. But i didn’t get any notifications.

**Comment by guillermobattistel** [comment]
Hi @hpsolver,

The backend team has deployed new changes today related to push notifications. Can you re-test? 

If you still face issues related to Push Notifications, please add the following information so we can analyze your particular case: 

- SDK version that you are using
- Are you running on an iPhone or Simulator ?  (VoIP push notifications doesn't work on Simulators)
- Are you running the sample app provided on this repo or is your own code? 
- Are you using PushKit? 

- Also please remember to verify that you have enabled PN on your app by going to your target > `Signin & Capabilities`

**Comment by hpsolver** [comment]
Hi @guillermobattistel 

Still i'm facing Push Notifications issue.


- SDK version : 'TelnyxRTC', '~> 0.1.2'

- running on an iPhone 

- own code

- yes i used PushKit

- PN already enabled

**Comment by hpsolver** [comment]
@guillermobattistel  thanks for update now is working fine 👍
