### ISSUE TITLE
Calling Isuue

### ISSUE THREAD

**Issue by hpsolver** [team-telnyx/telnyx-webrtc-ios#71]
If app is in terminated state and user accept call from notification then end the call is not notifying the caller is call ended.

**Comment by hpsolver** [comment]
@guillermobattistel any update on this ?

**Comment by guillermobattistel** [comment]
Hi @hpsolver , 
There's a backend fix that is in the pipeline to be tested.
I will updated when ready.

**Comment by RJSkorski** [comment]
@hpsolver The fix for the backend was applied. The issue should not be observed anymore.
