### ISSUE TITLE
After buying the new number Unable to start the native phone call.

### ISSUE THREAD

**Issue by iOS49** [team-telnyx/telnyx-webrtc-ios#79]
After buying the new number when i try to call on any number then it not contacting call and after 2-3 seconds receiving '**telnyx_rtc.bye**' listener. and it says the "**Connection has no Outbound Profile assigned D38**" and call disconnected.

we have verify the outbound profile from the telnyx side as well and we found the outbound profile. so please fix this point from SDK side ASAP.

Please find the attached screenshots below for more details.

Application log ScreenShot : 
![Screenshot 2022-11-25 at 11 18 35 AM](https://user-images.githubusercontent.com/119030643/203911553-520df33b-7de0-4cab-9261-647bbc530f49.png)

Telnyx profile SS:
![ss1](https://user-images.githubusercontent.com/119030643/203911562-5341226a-4f0a-4430-9988-ed7606311284.png)

**Comment by RJSkorski** [comment]
@iOS49 it is a question of the connection configuration. can you contact Telnyx support? they will be able to help you with that.
